managementapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from wtforms_sqlalchemy.fields import QuerySelectField

from ..models import Department, Role


class DepartmentForm(FlaskForm):
    """
    Form to add or edit a department
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

class RoleForm(FlaskForm):
    """
    Form to add or edit a role
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

class UserAssignForm(FlaskForm):
    """
    Form to assign departments and roles to users
    """
    department = QuerySelectField(query_factory=lambda: Department.query.all(),
                                  get_label=lambda x: x.name, get_pk=lambda x: x.id)  # important! prevents "ValueError: too many values to unpack (expected 2)"
    role = QuerySelectField(query_factory=lambda: Role.query.all(),
                            get_label=lambda x: x.name, get_pk=lambda x: x.id)
    submit = SubmitField('Submit')

managementapp/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

managementapp/user/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import user
from .forms import DepartmentForm, UserAssignForm, RoleForm
from .. import db
from ..models import Department, User, Role


# Department Views

@user.route('/departments', methods=['GET', 'POST'])
@login_required
def list_departments():
    """
    List all departments
    """
    departments = Department.query.all()

    return render_template('departments.html',
                           departments=departments, title="Departments")

@user.route('/departments/add', methods=['GET', 'POST'])
@login_required
def add_department():
    """
    Add a department to the database
    """
    add_department = True

    form = DepartmentForm()
    if form.validate_on_submit():
        department = Department(name=form.name.data,
                                description=form.description.data)
        try:
            # add department to the database
            db.session.add(department)
            db.session.commit()
            flash('You have successfully added a new department ', 'success')
        except:
            # in case department name already exists
            flash('Department name already exists', 'error')

        # redirect to departments page
        return redirect(url_for('user.list_departments'))

    # load department template
    return render_template('department.html', action="Add",
                           add_department=add_department, form=form,
                           title="Add Department")

@user.route('/departments/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_department(id):
    """
    Edit a department
    """
    add_department = False

    department = Department.query.get_or_404(id)
    form = DepartmentForm(obj=department)
    if form.validate_on_submit():
        department.name = form.name.data
        department.description = form.description.data
        db.session.commit()
        flash('You have successfully edited the department', 'success')

        # redirect to the departments page
        return redirect(url_for('user.list_departments'))

    form.description.data = department.description
    form.name.data = department.name
    return render_template('department.html', action="Edit",
                           add_department=add_department, form=form,
                           department=department, title="Edit Department")

@user.route('/departments/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_department(id):
    """
    Delete a department from the database
    """
    department = Department.query.get_or_404(id)
    db.session.delete(department)
    db.session.commit()
    flash('You have successfully deleted the department', 'success')

    # redirect to the departments page
    return redirect(url_for('user.list_departments'))

    return render_template(title="Delete Department")  # this return statement is redundant

# Role Views

@user.route('/roles')
@login_required
def list_roles():
    """
    List all roles
    """
    roles = Role.query.all()
    return render_template('roles.html',
                           roles=roles, title='Roles')

@user.route('/roles/add', methods=['GET', 'POST'])
@login_required
def add_role():
    """
    Add a role to the database
    """
    add_role = True

    form = RoleForm()
    if form.validate_on_submit():
        role = Role(name=form.name.data,
                    description=form.description.data)

        try:
            # add role to the database
            db.session.add(role)
            db.session.commit()
            flash('You have successfully added a new role', 'success')
        except:
            # in case role name already exists
            flash('Role name already exists', 'error')

        # redirect to the roles page
        return redirect(url_for('user.list_roles'))

    # load role template
    return render_template('role.html', add_role=add_role,
                           form=form, title='Add Role')

@user.route('/roles/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_role(id):
    """
    Edit a role
    """
    add_role = False

    role = Role.query.get_or_404(id)
    form = RoleForm(obj=role)
    if form.validate_on_submit():
        role.name = form.name.data
        role.description = form.description.data
        db.session.add(role)
        db.session.commit()
        flash('You have successfully edited the role', 'success')

        # redirect to the roles page
        return redirect(url_for('user.list_roles'))

    form.description.data = role.description
    form.name.data = role.name
    return render_template('role.html', add_role=add_role,
                           form=form, title="Edit Role")

@user.route('/roles/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_role(id):
    """
    Delete a role from the database
    """
    role = Role.query.get_or_404(id)
    db.session.delete(role)
    db.session.commit()
    flash('You have successfully deleted the role', 'success')

    # redirect to the roles page
    return redirect(url_for('user.list_roles'))

    return render_template(title="Delete Role")  # this return statement is redundant

# User Views

@user.route('/users')
@login_required
def list_users():
    """
    List all users
    """
    users = User.query.all()
    return render_template('users.html',
                           users=users, title='Users')

@user.route('/users/assign/<int:id>', methods=['GET', 'POST'])
@login_required
def assign_user(id):
    """
    Assign a department and a role to a user
    """
    user = User.query.get_or_404(id)

    form = UserAssignForm(obj=user)

    if form.validate_on_submit():
        user.department = form.department.data
        user.role = form.role.data
        db.session.add(user)
        db.session.commit()
        flash('You have successfully assigned a department and role', 'success')

        # redirect to the roles page
        return redirect(url_for('user.list_users'))

    return render_template('user.html',
                           user=user, form=form,
                           title='Assign User')

managementapp/templates/create_account.html
{% extends "base.html" %}
{% block title %}Create Account{% endblock %}
{% block head %}
<!-- Site Properties -->
<style type="text/css">
    body {
      background-color: rgb(255, 255, 255);
      font-family: 'Mandali';
    }

    button {
       font-family: 'Mandali';

}

    body > .grid {
      height: 100%;
    }
    .ui.large.form{
    font-size: 1em;
    }
    label{
      text-align: left;
    }

    @media only screen and (max-width: 600px)
    {
      #form-container {
        width: 80% !important;
      }
    }

    /* Remove annoying extra border at bottom of form box */
.ui.stacked.segment::after{
  border:none;
}

</style>
<script type="text/javascript">
$(function() {
	$('.ui.dropdown').dropdown();
});

  $(document)
    .ready(function() {
      $('.ui.form')
        .form({
          fields: {
            first_name: {
              identifier  : 'first_name',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your first name'
                },
                {
                  type   : 'length[3]',
                  prompt : 'Your first name must be at least 3 characters'
                }
              ]
            },
            last_name: {
              identifier  : 'last_name',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your last name'
                },
                {
                  type   : 'length[3]',
                  prompt : 'Your last name must be at least 3 characters'
                }
              ]
            },
            email: {
              identifier  : 'email',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your email'
                },
                {
                  type   : 'email',
                  prompt : 'Please enter a valid email'
                }
              ]
            },
            password: {
              identifier  : 'password',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your password'
                },
                {
                  type   : 'length[5]',
                  prompt : 'Your password must be at least 5 characters'
                }
              ]
          },
            confirm_password: {
              identifier  : 'confirm_password',
              rules: [
                {
                  type   : 'match[password]',
                  prompt : 'Passwords do not match'
                },
              ]
          },
         user_type: {
        identifier: 'user_type',
        rules: [
          {
            type   : 'empty',
            prompt : 'Please select an appropriate user type'
          }
        ]
      }},
          on: 'blur',
          inline: false
        })
      ;
    })
  ;



</script>
{% endblock %}
{% block body %}
<div class="ui middle aligned center aligned grid" style="background-color:white; margin-top:0px;">
    <div id="form-container" class="eight wide column" style="margin-top:4em; margin-bottom:8em">
        <h2 class="ui image header" style="color: #74D7D7; font-family: Josefin Slab; font-weight:400; font-size:2.5em">
            <div class="content">
                Register for an account
            </div>
        </h2>
        <form class="ui large form" method="post">
            {{ form.hidden_tag() }}
            <div class="ui stacked segment">
                <div class="field">
                    <label>First name</label>
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{ form.first_name(placeholder="First name") }}
                    </div>
                </div>
                <div class="field">
                    <label>Last name</label>
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{ form.last_name(placeholder="Last name") }}
                    </div>
                </div>
                <div class="field">
                    <label>Email address</label>
                    <div class="ui left icon input">
                        <i class="mail icon"></i>
                        {{ form.email(placeholder="Email address") }}
                    </div>
                </div>

                <div class="field">
                    <label>Password</label>
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.password(placeholder="Password") }}
                    </div>
                </div>
                <div class="field">
                    <label>Confirm password</label>
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.confirm_password(placeholder="Confirm password") }}
                    </div>
                </div>
                <button class="ui fluid large submit button" type="submit"
                        style="background-color:#74D7D7; font-family: 'Mandali'">Register
                </button>
            </div>

            <div id='login-flash-div' class="ui error message">{% with messages = get_flashed_messages() %}
                {% if messages %}
                <script type="text/javascript">
        document.getElementById("login-flash-div").className += " visible";

                </script>
                <ul class="list" style="margin:auto">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endwith %}
            </div>
        </form>
    </div>
</div>

{% endblock %}

managementapp/templates/department.html
{% extends "base.html" %}
{% block title %}
{% if add_department %}
Add Department
{% else %}
Edit Department
{% endif %}
{% endblock %}


{% block head %}
<!-- Site Properties -->
<!--<script src="{{ url_for('static', filename='login-page/jquery.js') }}"></script>-->
<!--<script src="{{ url_for('static', filename='login-page/form.js') }}"></script>-->
<!--<script src="{{ url_for('static', filename='login-page/transition.js') }}"></script>-->

<style type="text/css">
    body, {
      background-color: rgb(255, 255, 255);
      font-family: 'Mandali';
      color: #474747;
    }

    button {
       font-family: 'Mandali';

}

    body > .grid {
      height: 100%;
    }

    .ui.large.form{
    font-size: 1em;
    }

    @media only screen and (max-width: 600px)
    {
      #form-container {
        width: 80% !important;
      }
    }

    /* Remove annoying extra border at bottom of form box */
.ui.stacked.segment::after{
  border:none;
}


</style>
<script>
      $(document)
    .ready(function() {
      $('.ui.form')
        .form({
          fields: {
            name: {
              identifier  : 'name',
              rules: [
                {
                  type   : 'length[2]',
                  prompt : 'Department name should be at least 2 characters'
                },
              ]
            },
            description: {
              identifier  : 'description',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter a brief description for the department'
                },
              ]
            }
          },
          on: 'blur',
          inline: false
        })
      ;
    })
  ;

</script>
{% endblock %}
{% block body %}

<div class="ui middle aligned center aligned grid" style="background-color:white; margin-top:0px;">
    <div class="twelve wide column" style="margin-top:4em; margin-bottom:8em">
        <div class="ui center aligned grid">

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul class="list" style="margin:auto">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}

            <div class="twelve wide column">
                {% if add_department %}
                <h2 class="ui header"
                    style="color: #74D7D7; font-family: Josefin Slab; font-weight:400; font-size:2.5em">
                    Add department
                </h2>
                {% else %}
                <h2 class="ui header"
                    style="color: #74D7D7; font-family: Josefin Slab; font-weight:400; font-size:2.5em">
                    Edit department
                </h2>
                {% endif %}
            </div>

            <div class="twelve wide left aligned column">
                <form class="ui large form" method="post">
                    {{ form.hidden_tag() }}
                    <div class="ui stacked segment">
                        <div class="field">
                            <label>Department Name</label>
                            <div class="ui left icon input">
                                <i class="building icon"></i>
                                {{ form.name(placeholder="Department Name") }}
                            </div>
                        </div>
                        <div class="field">
                            <label>Department Description</label>

                            <div class="ui left icon input">
                                <i class="info circle icon"></i>
                                {{ form.description(placeholder="Description") }}
                            </div>
                        </div>
                        <button class="ui fluid medium submit button" type="submit"
                                style="background-color:#74D7D7; font-family: 'Mandali'">
                            {% if add_department %}
                            Add Department
                            {% else %}
                            Edit Department
                            {% endif %}
                        </button>
                    </div>
                    <div class="ui error message"></div>
                </form>
            </div>


        </div>
    </div>
</div>

{% endblock %}

managementapp/templates/departments.html
{% extends "base.html" %}
{% block title %}Departments{% endblock %}
{% block head %}
<!-- Site Properties -->
<link href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet"/>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<style type="text/css">
    body, {
      background-color: rgb(255, 255, 255);
      font-family: 'Mandali';
      color: #474747;
    }

    button {
       font-family: 'Mandali';

}

    body > .grid {
      height: 100%;
    }

    .ui.large.form{
    font-size: 1em;
    }

    #toast-container{
      top: 60px;
    }


</style>


{% endblock %}
{% block body %}

<div class="ui middle aligned center aligned grid" style="background-color:white; margin-top:0px;">
    <div class="twelve wide column" style="margin-top:4em; margin-bottom:8em">
        <div class="ui center aligned grid">

            <div class="sixteen wide column">
                <h2 class="ui header"
                    style="color: #74D7D7; font-family: Josefin Slab; font-weight:400; font-size:2.5em">
                    Departments
                </h2>
            </div>

            {% if departments %}
            <div class="sixteen wide column">
                <p style="color:#474747">The following departments are currently present in the database:
                </p>
                <div class="ui divider"></div>
            </div>
            <div class="sixteen wide column">

                <table class="ui celled table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Employee Count</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for department in departments %}
                    <tr>
                        <td> {{ department.name }}</td>
                        <td> {{ department.description }}</td>
                        <td>
                            {% if department.users %}
                            {{ department.users.count() }}
                            {% else %}
                            0
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ url_for('user.edit_department', id=department.id) }}">
                                <i class="fa fa-pencil"></i> Edit
                            </a>
                        </td>
                        <td>
                            <a href="{{ url_for('user.delete_department', id=department.id) }}">
                                <i class="fa fa-trash"></i> Delete
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="sixteen wide column">
                <h4 class="ui header">No departments have been added.</h4>
                <div class="ui divider"></div>
            </div>
            {% endif %}
            <div class="sixteen wide column">
                <a href="{{ url_for('user.add_department') }}" class="ui medium button">
                    <i class="fa fa-plus"></i>
                    Add Department
                </a>
            </div>

            <!--Display success flashes as toasts-->
            {% with messages = get_flashed_messages(category_filter=["success"]) %}
            {% if messages %}
            <script>
            // Display a success toast with title
            {% for message in messages %}
            toastr.success('{{ message }}', 'Success')
            {% endfor %}

            </script>
            {% endif %}
            {% endwith %}

            <!--Display error flashes as toasts-->
            {% with messages = get_flashed_messages(category_filter=["error"]) %}
            {% if messages %}
            <script>
            // Display an error toast with title
            {% for message in messages %}
            toastr.error('{{ message }}', 'Error')
            {% endfor %}

            </script>
            {% endif %}
            {% endwith %}
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}

{% endblock %}

managementapp/templates/roles.html
{% extends "base.html" %}
{% block title %}Roles{% endblock %}
{% block head %}
<!-- Site Properties -->
<!--<script src="{{ url_for('static', filename='login-page/jquery.js') }}"></script>-->
<!--<script src="{{ url_for('static', filename='login-page/form.js') }}"></script>-->
<link href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet"/>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<style type="text/css">
    body, {
      background-color: rgb(255, 255, 255);
      font-family: 'Mandali';
      color: #474747;
    }

    button {
       font-family: 'Mandali';

}

    body > .grid {
      height: 100%;
    }

    .ui.large.form{
    font-size: 1em;
    }
    #toast-container{
      top: 60px;
    }


</style>


{% endblock %}
{% block body %}

<div class="ui middle aligned center aligned grid" style="background-color:white; margin-top:0px;">
    <div class="twelve wide column" style="margin-top:4em; margin-bottom:8em">
        <div class="ui center aligned grid">

            <div class="sixteen wide column">
                <h2 class="ui header"
                    style="color: #74D7D7; font-family: Josefin Slab; font-weight:400; font-size:2.5em">
                    Roles
                </h2>
            </div>

            {% if roles %}
            <div class="sixteen wide column">
                <p style="color:#474747">The following roles are currently present in the database:
                </p>
                <div class="ui divider"></div>
            </div>
            <div class="sixteen wide column">

                <table class="ui celled table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>User Count</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for role in roles %}
                    <tr>
                        <td> {{ role.name }}</td>
                        <td> {{ role.description }}</td>
                        <td>
                            {% if role.users %}
                            {{ role.users.count() }}
                            {% else %}
                            0
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ url_for('user.edit_role', id=role.id) }}">
                                <i class="fa fa-pencil"></i> Edit
                            </a>
                        </td>
                        <td>
                            <a href="{{ url_for('user.delete_role', id=role.id) }}">
                                <i class="fa fa-trash"></i> Delete
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="sixteen wide column">
                <h4 class="ui header">No roles have been added.</h4>
                <div class="ui divider"></div>
            </div>
            {% endif %}
            <div class="sixteen wide column">
                <a href="{{ url_for('user.add_role') }}" class="ui medium button">
                    <i class="fa fa-plus"></i>
                    Add Role
                </a>
            </div>

            <!--Display success flashes as toasts-->
            {% with messages = get_flashed_messages(category_filter=["success"]) %}
            {% if messages %}
            <script>
            // Display a success toast with title
            {% for message in messages %}
            toastr.success('{{ message }}', 'Success')
            {% endfor %}

            </script>
            {% endif %}
            {% endwith %}

            <!--Display error flashes as toasts-->
            {% with messages = get_flashed_messages(category_filter=["error"]) %}
            {% if messages %}
            <script>
            // Display an error toast with title
            {% for message in messages %}
            toastr.error('{{ message }}', 'Error')
            {% endfor %}

            </script>
            {% endif %}
            {% endwith %}
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}

{% endblock %}

managementapp/templates/users.html
{% extends "base.html" %}
{% block title %}Users{% endblock %}
{% block head %}
<!-- Site Properties -->
<!--<script src="{{ url_for('static', filename='login-page/jquery.js') }}"></script>-->
<!--<script src="{{ url_for('static', filename='login-page/form.js') }}"></script>-->
<link href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet"/>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<style type="text/css">
    body, {
      background-color: rgb(255, 255, 255);
      font-family: 'Mandali';
      color: #474747;
    }

    button {
       font-family: 'Mandali';

}

    body > .grid {
      height: 100%;
    }

    .ui.large.form{
    font-size: 1em;
    }

    #toast-container{
      top: 60px;
    }




</style>


{% endblock %}
{% block body %}

<div class="ui middle aligned center aligned grid" style="background-color:white; margin-top:0px;">
    <div class="twelve wide column" style="margin-top:4em; margin-bottom:8em">
        <div class="ui center aligned grid">

            <div class="sixteen wide column">
                <h2 class="ui header"
                    style="color: #74D7D7; font-family: Josefin Slab; font-weight:400; font-size:2.5em">
                    Users
                </h2>
            </div>

            {% if users %}
            <div class="sixteen wide column">
                <p style="color:#474747">The following users are currently present in the database:</p>
                <div class="ui divider"></div>
            </div>
            <div class="sixteen wide column">

                <table class="ui celled table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Department</th>
                        <th>Role</th>
                        <th>Assign</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                    <tr>
                        <td> {{ user.first_name }} {{ user.last_name }}</td>
                        <td>
                            {% if user.department %}
                            {{ user.department.name }}
                            {% else %}
                            -
                            {% endif %}
                        </td>
                        <td>
                            {% if user.role %}
                            {{ user.role.name }}
                            {% else %}
                            -
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ url_for('user.assign_user', id=user.id) }}">
                                <i class="fa fa-user-plus"></i> Assign
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}

            <!--Display success flashes as toasts-->
            {% with messages = get_flashed_messages(category_filter=["success"]) %}
            {% if messages %}
            <script>
            // Display a success toast with title
            {% for message in messages %}
            toastr.success('{{ message }}', 'Success')
            {% endfor %}


            </script>
            {% endif %}
            {% endwith %}

            <!--Display error flashes as toasts-->
            {% with messages = get_flashed_messages(category_filter=["error"]) %}
            {% if messages %}
            <script>
            // Display an error toast with title
            {% for message in messages %}
            toastr.error('{{ message }}', 'Error')
            {% endfor %}


            </script>
            {% endif %}
            {% endwith %}
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}